index:
  path: /
  controller: App\Controller\IndexController::index
api:
  path: /api/products/recommended/{city}
  controller: App\Controller\RecommendedProductsController::getRecommendedProduct
cityList:
  path: api/city/list
  controller: App\Controller\CityListController::index